// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WH0VjTezzK3-pgDNG7qQOPPnuL1I6Mc',
    appId: '1:1046325272025:web:7175d9b23935abb8f08dc8',
    messagingSenderId: '1046325272025',
    projectId: 'tapservice-1111',
    authDomain: 'tapservice-1111.firebaseapp.com',
    storageBucket: 'tapservice-1111.appspot.com',
    measurementId: 'G-BC4RLYB60R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARYchwg9SU85-S57jz3rViKV02TUkBSvo',
    appId: '1:1046325272025:android:4287a92a30f1f73af08dc8',
    messagingSenderId: '1046325272025',
    projectId: 'tapservice-1111',
    storageBucket: 'tapservice-1111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhClUNFI1qgxp9bIcK2BSXl5aidxixQI',
    appId: '1:1046325272025:ios:acb2ebb5f10618f5f08dc8',
    messagingSenderId: '1046325272025',
    projectId: 'tapservice-1111',
    storageBucket: 'tapservice-1111.appspot.com',
    iosBundleId: 'com.example.projetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhClUNFI1qgxp9bIcK2BSXl5aidxixQI',
    appId: '1:1046325272025:ios:0bf586d4d928380af08dc8',
    messagingSenderId: '1046325272025',
    projectId: 'tapservice-1111',
    storageBucket: 'tapservice-1111.appspot.com',
    iosBundleId: 'com.example.projetoFinal.RunnerTests',
  );
}
